//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyPrinters
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public int EngenPrintersID { get; set; }
        public string PrinterName { get; set; }
        public string FolderToMonitor { get; set; }
        public string OutputType { get; set; }
        public string FileOutput { get; set; }
        public bool Active { get; set; }
        public int PrinterMakeID { get; set; }
        public System.DateTime CreatedTimeStamp { get; set; }
    
        public virtual PrinterMake PrinterMake { get; set; }
    }
}
