//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyPrinters
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterMake
    {
        public PrinterMake()
        {
            this.Printers = new HashSet<Printer>();
        }
    
        public int PrinterMakeID { get; set; }
        public string PrinterMakeName { get; set; }
    
        public virtual ICollection<Printer> Printers { get; set; }
    }
}
